image: docker:test
services:
  - name: docker:test-dind
    command: ["--experimental"]

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/opensuse-kernel-deploy:latest
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/opensuse-kernel-deploy:$CI_COMMIT_REF_SLUG
  DOCKER_CLI_EXPERIMENTAL: enabled
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
  - mkdir -p ~/.docker/cli-plugins/ && wget https://github.com/docker/buildx/releases/download/v0.2.2/buildx-v0.2.2.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx && chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap

stages:
  - build
  - test
  - release

build image:
  stage: build
  script:
    - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t $CONTAINER_TEST_IMAGE --push .

inspect image:
  stage: test
  script:
    - docker buildx imagetools inspect $CONTAINER_TEST_IMAGE

release image:
  stage: release
  script:
    - docker buildx imagetools create -t $CONTAINER_RELEASE_IMAGE $CONTAINER_TEST_IMAGE
    - docker buildx imagetools inspect $CONTAINER_RELEASE_IMAGE
  only:
    - opensuse-kernel-deploy
