name: Docker Image CI

on:
  push:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: leap:15.2
            tag: 15.2
          - version: leap:15.3
            tag: 15.3
          - version: leap:15.4
            tag: 15.4
          - version: tumbleweed
            tag: latest

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to registry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
    - name: Setup buildx plugin
      run: |
        docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        mkdir -p ~/.docker/cli-plugins/
        wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        docker buildx create --name xbuilder --use
        docker buildx inspect --bootstrap
    - name: Build the Docker image for ${{ matrix.tag }}
      run: docker buildx build --build-arg VERSION=${{ matrix.version }} --platform linux/arm/v7,linux/arm64,linux/amd64 -t ghcr.io/${{ github.repository }}/opensuse-salt:${{ matrix.tag }} --push .
